name: 🐛 Bug Report - Beta Version
description: Report a bug in the beta/development version
title: "[BETA] "
labels: ["bug", "beta"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for testing the beta version! Please fill out this form to help us fix the issue.

  - type: checkboxes
    id: version-check
    attributes:
      label: Version Check
      description: Please confirm you are using the beta version
      options:
        - label: I am using the beta version (dev branch), NOT the stable release
          required: true
        - label: I have checked that this bug does not exist in the stable version
          required: false

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Edge
        - Brave
        - Other (specify in description)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser? (e.g., 120.0.1)
      placeholder: "120.0.1"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of the extension? (check in browser extensions page)
      placeholder: "e.g., 1.2.0-beta"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or describe what you see
    validations:
      required: false

  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs / Error Messages
      description: |
        If applicable, open the browser console (F12) and paste any error messages here
      placeholder: Paste error messages here...
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: additional
    attributes:
      label: Additional Context
      options:
        - label: This is a new bug (didn't exist in previous beta versions)
        - label: I can consistently reproduce this bug
        - label: The bug breaks core functionality
        - label: I would like to help fix this bug
